ngageoint/mage-server

functionalTests/testRecordings.js

- this file is a mock api call for http requests

fix for unit tests

---

CHANGELOG.md
public/app/factories/local-storage.service.js
public/app/filters/moment.filter.js
public/app/mage/mage-nav.controller.js
public/app/observation/form/date.edit.html
public/app/observation/form/date.edit.js
public/app/observation/form/form.directive.html
public/app/observation/observation-feed.directive.html
public/app/observation/observation-feed.directive.js
public/app/user/user-feed.directive.html
public/app/user/user-feed.directive.js
public/dist/index.html
public/package.json

* Users can edit observation time in GMT or Local time.
* Users can view observation and location time as relative or absolute local or GMT.

Add Time Preferences

---

test/device/deviceCreateTest.js

Implementing auto-register tests.

Fix broken tests

---

web-app/src/ng1/admin/admin.dashboard.component.js
web-app/src/ng1/admin/admin.dashboard.html
web-app/src/ng1/admin/devices/device.component.js
web-app/src/ng1/admin/devices/device.html
web-app/src/ng1/admin/events/event.access.component.js
web-app/src/ng1/admin/events/event.access.html
web-app/src/ng1/admin/events/event.component.js
web-app/src/ng1/admin/events/event.html
web-app/src/ng1/admin/teams/team.access.component.js
web-app/src/ng1/admin/teams/team.access.html
web-app/src/ng1/admin/teams/team.component.js
web-app/src/ng1/admin/teams/team.html
web-app/src/ng1/admin/users/user.component.js
web-app/src/ng1/admin/users/user.html
web-app/src/ng1/css/style.scss
web-app/src/ng1/material-components/typeahead.select.component.html

1. Fixing typeahead menu location
2. Removing static status display for loading search results

Page users 2

---

migrations/018-set-default-password-policy.js
models/user.js
routes/setup.js
routes/users.js
test/passwordValidatorTest.js
test/user/userCreateTest.js
test/user/userUpdateTest.js
utilities/passwordValidator.js
web-app/src/ng1/admin/settings/passwordHelpBuilder.js
web-app/src/ng1/admin/settings/settings.component.js
web-app/src/ng1/admin/settings/settings.html
web-app/src/ng1/admin/users/user.edit.component.js
web-app/src/ng1/admin/users/user.edit.html
web-app/src/ng1/setup/setup.controller.js
web-app/src/ng1/user/profile.component.js
web-app/src/ng1/user/profile.html
web-app/src/ng1/user/user.reset.password.controller.js
web-app/src/ng1/user/user.reset.password.html

Adding password policy functionality to admin settings.  Admins now have more control, if they wish, on how users create passwords.  Things like minimum lowercase letters, special characters, etc. are now available for password policy enforcement.

Password enhancement

---

CHANGELOG.md
models/team.js
web-app/src/ng1/admin/admin.dashboard.component.js
web-app/src/ng1/admin/admin.dashboard.html
web-app/src/ng1/admin/devices/device.component.js
web-app/src/ng1/admin/devices/device.edit.component.js
web-app/src/ng1/admin/devices/device.edit.html
web-app/src/ng1/admin/devices/device.html
web-app/src/ng1/admin/events/event.access.component.js
web-app/src/ng1/admin/events/event.access.html
web-app/src/ng1/admin/events/event.component.js
web-app/src/ng1/admin/events/event.html
web-app/src/ng1/admin/teams/team.access.component.js
web-app/src/ng1/admin/teams/team.access.html
web-app/src/ng1/admin/teams/team.component.js
web-app/src/ng1/admin/teams/team.html
web-app/src/ng1/admin/users/user.component.js
web-app/src/ng1/admin/users/user.html

Misc. bug fixes introduced with paging feature.

Paging bug fixes

---

CHANGELOG.md
migrations/018-set-default-password-policy.js
migrations/019-add-password-history-setting.js
migrations/019-update-password-policy.js
models/user.js
test/passwordPolicyEnforcerTest.js
test/passwordValidatorTest.js
utilities/passwordPolicyEnforcer.js
utilities/passwordValidator.js
web-app/src/ng1/admin/settings/settings.component.js
web-app/src/ng1/admin/settings/settings.html

Adding password history feature.

Enhance password policy

---

CHANGELOG.md
routes/users.js
web-app/src/ng1/admin/users/user.edit.component.js
web-app/src/ng1/admin/users/user.edit.html
web-app/src/ng1/user/user-icon.directive.js

User map icon

---

CHANGELOG.md
web-app/src/ng1/admin/admin.dashboard.html
web-app/src/ng1/admin/devices/device.html
web-app/src/ng1/admin/events/event.html
web-app/src/ng1/admin/layers/layer.html
web-app/src/ng1/admin/teams/team.html
web-app/src/ng1/admin/users/user.html

Adding icons to team/event search results to help with clarity.

Team event clarify

---

authentication/geoaxis.js
authentication/google.js
authentication/ldap.js
authentication/login-gov.js
authentication/saml.js
migrations/022-copy-auth-from-config-to-db.js
migrations/024-link-auth-to-auth-config.js
models/authentication.js
models/authenticationconfiguration.js
routes/authenticationconfigurations.js
web-app/src/app/admin/admin-settings/admin-settings.model.ts
web-app/src/app/admin/admin-settings/authentication-delete/authentication-delete.component.html
web-app/src/app/admin/admin-settings/authentication-delete/authentication-delete.component.scss
web-app/src/app/admin/admin-settings/authentication-delete/authentication-delete.component.ts
web-app/src/app/app.module.ts
web-app/src/app/upgrade/ajs-upgraded-providers.ts
web-app/src/ng1/admin/users/user.html
web-app/src/ng1/factories/authentication-configuration.service.js

Bug: Handling removal of auth strategy.

Delete auth strategy

---

web-app/src/app/admin/admin-settings/security-disclaimer/security-disclaimer.component.html
web-app/src/app/admin/admin-settings/security-disclaimer/security-disclaimer.component.ts
web-app/src/app/admin/admin-settings/security-disclaimer/security-disclaimer.model.ts

Saving correct properties on the disclaimer.

Saving disclaimer with correct properties

---

web-app/src/app/export/export-data/export-data.component.html
web-app/src/app/export/export-data/export-data.component.spec.ts
web-app/src/app/export/export-dialog.component.html
web-app/src/app/export/export-dialog.component.scss
web-app/src/app/export/export-dialog.component.spec.ts
web-app/src/app/export/export.component.spec.ts

Fixing formatting of options
Fixing tests

Export dialog cleanup

---

web-app/src/app/app.module.ts
web-app/src/app/export/empty-state/no-exports.component.html
web-app/src/app/export/empty-state/no-exports.component.scss
web-app/src/app/export/empty-state/no-exports.component.spec.ts
web-app/src/app/export/empty-state/no-exports.component.ts
web-app/src/app/export/export-dialog.component.html
web-app/src/app/export/export-dialog.component.ts

Showing an empty state on the export dialog.

Export dialog empty state

---

service/src/api/field/geometryField.js
service/src/export/geopackage.js
service/src/routes/exports.js
service/test/export/geopackageTest.js

Adding bounds to geopackage export so that "zoom to" operations work.

Geo export

---

CHANGELOG.md
service/src/docs/openapi.yaml
service/src/export/csv.js
service/src/export/exporter.js
service/src/export/geojson.js
service/src/export/geopackage.js
service/src/export/kml.js
service/src/export/kmlWriter.js
service/src/models/device.js
service/src/models/location.js
service/src/models/observation.js
service/src/models/user.js
service/src/routes/exports.js
service/test/export/csvTest.js
service/test/export/geopackageTest.js
service/test/location/locationReadTest.js

Reducing memory usage when exporting.

Export oom

---

web-app/src/app/app.module.ts
web-app/src/app/geometry/geometry-dms.spec.ts
web-app/src/app/geometry/geometry-dms.ts
web-app/src/app/geometry/geometry.pipe.ts
web-app/src/app/observation/observation-edit/observation-edit-geometry/observation-edit-geometry-form.component.html
web-app/src/app/observation/observation-edit/observation-edit-geometry/observation-edit-geometry-form.component.ts
web-app/src/ng1/filters/geometry.filter.js
web-app/src/ng1/mage/navbar/preferences-button.component.html

* DMS editing in observation location edit
* Added DMS to coordinate display options

Degrees Minutes Seconds

---

CHANGELOG.md
web-app/angular.json
web-app/package-lock.json
web-app/package.json
web-app/src/app/map/leaflet.component.ts
web-app/src/ng1/factories/map.service.js
web-app/src/ng1/leaflet-extensions/grid/gars/GARSLayer.ts
web-app/src/ng1/leaflet-extensions/grid/gars/TileDraw.ts
web-app/src/ng1/leaflet-extensions/grid/mgrs/MGRSLayer.ts
web-app/src/ng1/leaflet-extensions/grid/mgrs/TileDraw.ts
web-app/src/ng1/leaflet-extensions/index.js
web-app/src/ng1/mage/leaflet.component.js

feat: mgrs grid capability

---

plugins/geoserver/package.json
plugins/image/service/package-lock.json
plugins/image/service/package.json
service/package-lock.json
service/package.json
service/src/models/event.js
service/test/event/eventCreateTest.js
service/test/event/eventDeleteTest.js
web-app/src/ng1/admin/events/event.component.js

* Handle form reordering on the Event admin page with regards to archived forms.
* Bump mongoose to 6.7.1
* MAGE-1042

fix: Event form reordering

---

service/src/adapters/systemInfo/adapters.systemInfo.controllers.web.ts
service/src/adapters/systemInfo/adapters.systemInfo.service.ts
service/src/app.api/systemInfo/app.api.systemInfo.ts
service/src/app.impl/systemInfo/app.impl.systemInfo.ts
service/src/app.ts
service/src/entities/systemInfo/entities.systemInfo.ts
service/test/adapters/systemInfo/adapters.systemInfo.controllers.web.test.ts
service/test/app/systemInfo/app.systemInfo.test.ts
web-app/src/ng1/about/about.html
web-app/src/ng1/admin/events/events.component.js
web-app/src/ng1/admin/events/events.html
web-app/src/ng1/admin/users/users.component.js
web-app/src/ng1/factories/user.service.js

Enable's conditional access to system information based on the user's authentication status. It checks for the presence of an Authorization header and authenticates the user accordingly. If the header is missing, the request still proceeds, allowing for conditional responses based on authentication status.
This update allows our application to provide basic system information to unauthenticated users while reserving more detailed data for authenticated users, and makes sensitive information only accessible to authenticated users with appropriate permissions.

Conditional access to System Info

---

plugins/random/src/random.ts
plugins/random/src/topics/random.ts
web-app/src/app/feed/feed-list/feed-list.component.ts

Make sure the feed list does not display the wrong content from a previously selected feed tab.

Feed list switcharoo

---

plugins/random/package-lock.json
plugins/random/package.json
plugins/random/src/random.ts
plugins/random/src/topics/random.ts

Add options to return multiple random items in feeds from the random plugin to support testing.

Random multiplicity

---

README.md

Modified readme to include versions of mongodb and nodejs for new developers to indicate the best/desired versions for development.

add mongodb and nodejs desired version

---

plugins/arcgis/service/src/ArcGISIdentityManagerFactory.ts
plugins/arcgis/service/src/FeatureService.ts
plugins/arcgis/service/src/index.ts

Moving logic from FeatureService to a factory for creating IdentityManager.
Also, there are some TODOs to work through from observations.

Add ArcGISIdentityManagerFactory

---

plugins/arcgis/web-app/projects/main/src/lib/arc-event/arc-event.component.html
plugins/arcgis/web-app/projects/main/src/lib/arc-event/arc-event.component.scss
plugins/arcgis/web-app/projects/showcase/src/app/arc.service.mock.ts

Updated material in arcGIS events

Arc event material updates

---

README.md
plugins/arcgis/README.md

Added instructions for adding OAuth to Feature Layer services for ArcGIS

1396 - OAuth Spike

---

.github/workflows/release.arcgis_plugin.yaml
.github/workflows/release.sftp_plugin.yaml
.github/workflows/release.yaml

separate out package deployments to allow failures

---

Dockerfile
plugins/sftp/service/package-lock.json
plugins/sftp/service/package.json

Updated the dockerfile to use the correct folder structure that aligns with the arcgis plugin.
Updated the sftp plugin express version to align with the arcgis plugin

Fix sftp docker build

---

README.md
service/functionalTests/config/testConfig.json
service/functionalTests/testRecordings.js
service/src/docs/openapi.yaml

- removed/replaced all instances of previous project name:
+ **Mobile Awareness GEOINT Environment** --> **MAGE**

1424 - Mage name change

---

service/src/routes/imports.js

When trying to upload a file for a Layer it was causing the app to crash every time for KML files. Secondly there was an error when displaying the filename after success if it was in most languages other than English.

1402 - Arabic Character in filename bug

---

.github/workflows/aws_dev.deploy.yaml

update workflow file to include proper variables in push command

update env variables for docker push command

---

.gitignore
Dockerfile
docker-compose.yml
docker/docker-compose.yml
docker/server/Dockerfile
plugins/image/service/package-lock.json
plugins/image/service/package.json

Upgrade to using bitnami images to align with production
upgrade containers for new build/push to production.

Upgrade container images

---

web-app/admin/src/ng1/navbar/navbar.component.js

This pr fixes the logout button on the admin page to bring up the login modal.

Fix logging out from admin page.

---

plugins/sftp/service/package-lock.json

fix sftp package lock so that it can build

update package lock file

---

docker/server/Dockerfile
plugins/arcgis/service/package-lock.json
plugins/arcgis/service/package.json
plugins/arcgis/web-app/package-lock.json
plugins/arcgis/web-app/package.json
plugins/arcgis/web-app/projects/main/package-lock.json
plugins/arcgis/web-app/projects/main/package.json
plugins/sftp/service/package-lock.json
plugins/sftp/service/package.json
plugins/sftp/web/package-lock.json
plugins/sftp/web/package.json
plugins/sftp/web/projects/main/package-lock.json
plugins/sftp/web/projects/main/package.json

Updates Arcgis and SFTP plugins for 1.0.0-beta.2 release.

Release 1.0.0-beta.2 for Arcgis and SFTP plugins

---

docker/server/Dockerfile
instance/package.json
package-lock.json
package.json
plugins/arcgis/service/package-lock.json
plugins/arcgis/service/package.json
plugins/arcgis/web-app/package-lock.json
plugins/arcgis/web-app/package.json
plugins/arcgis/web-app/projects/main/package-lock.json
plugins/arcgis/web-app/projects/main/package.json
plugins/sftp/service/package-lock.json
plugins/sftp/service/package.json
plugins/sftp/web/package-lock.json
plugins/sftp/web/package.json
plugins/sftp/web/projects/main/package-lock.json
plugins/sftp/web/projects/main/package.json
service/npm-shrinkwrap.json
service/package.json
web-app/package-lock.json
web-app/package.json
web-app/projects/core-lib/package-lock.json
web-app/projects/core-lib/package.json

This PR updates the mage version to 6.4.0-beta.1.

Beta Release 6.4.0-beta.1

---

CODEOWNERS
package-lock.json
web-app/package-lock.json
web-app/src/app/preferences/time-format/time-format.component.ts

changed time format option from '30 seconds' to 'Relative'

---

web-app/admin/src/app/logins/logins.component.html
web-app/admin/src/app/logins/logins.component.scss

During the change to a unified Logins table across all admin pages, it seems that the pagination was lost and the ability to hide the filters was also removed. 
Both of these features have been re-added. 
Thus far, this feature is only added on the Admin Dashboard, and on the Individual User Pages, both need to be checked.

Fix missing paging and Re-add filter collapse
