- api/attachment.js
- api/form.js
- api/icon.js
- api/observation.js
- api/user.js
- app.js
- config.js
- manifest.yml
- package.json
- s3ctrl.sh
- setup.js
- Add s3fs support for keeping attachments, users, icons in Amazon S3 storage
- Add support for getting IP/Port from cloud foundry env variables
- Add support for getting MongoDB connection from cloud foundry
- Add manifest for deploying to CloudFoundry with "cf push"
- Make MAGE set up required DB entries on app start instead of manual migration script
> Make MAGE ready for CloudFoundry (PaaS) deployment

- test/attachment/attachmentDeleteTest.js
The typo otherwise causes "npm test" to fail.
> Fix typo in attachmentDeleteTest.js from ../MockTest to ../mockTest

- CHANGELOG.md
- service/src/routes/authenticationconfigurations.js
- web-app/src/app/admin/admin-authentication/admin-authentication-delete/admin-authentication-delete.component.ts
- web-app/src/app/admin/admin-authentication/admin-authentication.component.ts
- web-app/src/app/admin/admin-settings/admin-settings.component.html
- web-app/src/app/admin/admin-settings/admin-settings.component.spec.ts
- web-app/src/app/admin/admin-settings/admin-settings.component.ts
* Preventing all authentications from being disabled
> fix: prevent auth disable

- service/src/adapters/icons/adapters.icons.db.mongoose.ts
- service/test/adapters/icons/adapters.icons.db.mongoose.test.ts
- service/test/app/systemInfo/app.systemInfo.test.ts
- service/test/init.test.ts
…s/48886 that causes tests to fail using deep equals assertion on url objects
> Node 18.17 48886 url deep equal assertion

- service/.gitignore
- service/src/adapters/users/adapters.users.controllers.web.ts
- service/src/adapters/users/adapters.users.db.mongoose.ts
- service/src/app.impl/users/app.impl.users.ts
- service/src/entities/entities.global.ts
- service/test/entities/observations/entities.observations.test.ts
- web-app/post_build.js
- web-app/src/ng1/admin/admin.component.js
- web-app/src/ng1/admin/admin.dashboard.component.js
- web-app/src/ng1/admin/admin.dashboard.html
- web-app/src/ng1/admin/users/users.component.js
- web-app/src/ng1/admin/users/users.html
- web-app/src/ng1/app.js
- web-app/src/ng1/factories/user-paging.service.js
- web-app/src/ng1/factories/user.service.js
- web-app/tsconfig.app.json
This merge contains the recently merged changes on master to address the admin page user search bug.
> Merge master to develop

- service/src/app.impl/systemInfo/app.impl.systemInfo.ts
- service/src/entities/systemInfo/entities.systemInfo.ts
- service/test/adapters/systemInfo/adapters.systemInfo.controllers.web.test.ts
Fixed regression introduced on the *develop* branch's TS migration blocking initial admin user setup on first run.
We had missed the initial property on the **/api** endpoint's response which was being checked in Angular to see if zero users exist on the server, at which point we should route the user to the create an admin user flow instead of prompting them to login (as it currently works on *master*). This change replaces it, though it's leveraging the legacy JS user model for the moment for simplicity's sake.
Talking to Robert, there's an upcoming plan to migrate this behavior to a secret-based approach so we don't race to create the first admin user after installing and launching the server for the first time. But this unblocks the situation for now on wholly new installs until that …
> Bugfix: /api initial flag regression

- README.md
- web-app/src/ng1/admin/events/events.component.js
eventSearch was uninitialized, causing the event filter to malfunction on page load.  Initialize the eventSearch string to ''.
> initialize event search with empty string

- plugins/arcgis/service/package-lock.json
- plugins/arcgis/service/package.json
- plugins/arcgis/service/src/ArcGISConfig.ts
- plugins/arcgis/service/src/index.ts
- plugins/arcgis/web-app/projects/main/src/lib/ArcGISConfig.ts
- plugins/arcgis/web-app/projects/main/src/lib/arc-layer/arc-layer.component.html
- plugins/arcgis/web-app/projects/main/src/lib/arc-layer/arc-layer.component.ts
Provides draft for peer review for adding username/password authentication with ArcGIS server. 
Things to possibly do yet
1. Update UI webapp to provide username/password options or token with url, remove hardcoded section for testing
2. Testing and handle use cases beyond happy path
3. Move getServerUrl to Helper file
4.  Move getPortalUrl to Helper file
5. Update layer token to get token from identity manager
6. Move plugins/arcgis/web-app/projects/main/src/lib/arc-layer/arc-layer.component.ts addLayer to helper file and use instead of encodeURIComponent
7. Provide ability to refresh token upon expiration (if needed)
8. Any remaining TODOs
> arcgis username and password authentication

- plugins/arcgis/service/src/ArcGISConfig.ts
- plugins/arcgis/service/src/HttpClient.ts
- plugins/arcgis/service/src/ObservationProcessor.ts
- plugins/arcgis/service/src/index.ts
- plugins/arcgis/web-app/projects/main/src/lib/arc.service.ts
This PR creates the server side stuff needed to create and store the tokens generated from user initiated OAuth.
TODOs:
- Return request from initial authorization so that opened window is not left open
- Pass data through OAuth flow another way if possible. Currently need to create a temp feature service during flow to store tokens and needed creds
- Add error handling when using tokens
- Hide tokens from being passed back to client
> Add support for user OAuth

- plugins/arcgis/web-app/projects/showcase/src/app/arc.service.mock.ts
replaced EventResult with MageEvent to get showcase up and going again
> updated showcase to reflect recent changes

- plugins/arcgis/web-app/projects/main/src/lib/arc-admin/arc-admin.component.html
- plugins/arcgis/web-app/projects/main/src/lib/arc-admin/arc-admin.component.scss
- plugins/arcgis/web-app/projects/main/src/lib/arc-admin/arc-admin.component.ts
- plugins/arcgis/web-app/projects/main/src/lib/arc-event/arc-event.component.html
- plugins/arcgis/web-app/projects/main/src/lib/arc-layer/arc-layer-delete-dialog.component.spec.ts
- plugins/arcgis/web-app/projects/main/src/lib/arc-layer/arc-layer-dialog.component.spec.ts
- plugins/arcgis/web-app/projects/main/src/lib/arc-layer/arc-layer.component.html
- plugins/arcgis/web-app/projects/main/src/lib/arc-layer/arc-layer.component.scss
- plugins/arcgis/web-app/projects/showcase/src/app/app.component.spec.ts
- plugins/arcgis/web-app/projects/showcase/src/app/arc.service.mock.ts
pulled arc-admin attributes form out of pop-up and into page. Updated html. Fixed tests.
> Arc admin attribute form

- CHANGELOG.md
- README.md
- service/src/models/event.js
When using mongo db > 5.0.1, there was an issue that occurred due to a schema constraint in the EventSchema. The unique value must be a boolean. Switching this allowed for successful use with mongoDB 5.0.1 and mongoDB 6.0
> Event schema unique fix

- .github/workflows/build_test.image.service.yaml
- plugins/image/service/package-lock.json
- plugins/image/service/package.json
fix issues with building container for pushing to dev environment. temp fixes for the image service build/test steps
> Container build fix

- .github/workflows/build_test.sftp.service.yaml
- .github/workflows/build_test.sftp.web-app.yaml
- .github/workflows/release.sftp_plugin.yaml
Due to how workflows are enabled in github, we need to put out initial sftp workflows so we can properly utilize them from the branch as we make updates.
> initial sftp workflows into main branch

- web-app/angular.json
- web-app/package-lock.json
- web-app/src/app/about/about.component.html
- web-app/src/app/about/about.component.scss
- web-app/src/app/about/about.component.ts
A Contact Us Form is Needed to allow users to call or email for support. 
Testing instructions:
- Build Web App
- Run Mage Server Locally
- Navigate to `http://localhost:4242/#/about`
- Alternatively for sanity checks navigate to `http://localhost:4242/` and click the information icon in the top menu
- Note the Layout Changes
- Note the New Contact Us Section
- Click on the e-mail address
- Expected Result is email app is opened and `to:` field is populated with correct address
> Create Contact Us Section on Info Page

- Dockerfile
- docker/docker-compose.yml
- docker/server/Dockerfile
- plugins/image/service/package-lock.json
- plugins/image/service/package.json
Update docker files
Update package json for image service plugin
> update docker files

- web-app/admin/src/ng1/admin/events/event.html
- web-app/admin/src/ng1/css/admin/team/team.scss
- Layers descriptions that are long cause a weird display issue on the *events* page.
> 1420 - Event Layer Description

- web-app/admin/src/ng1/app.js
- web-app/src/app/navigation/navigation.component.html
- web-app/src/app/navigation/navigation.component.ts
This PR fixes an issue where the admin button appears for non admin users.
Admin user navbar
Non admin navbar
> Admin button should appear only for Admins

- web-app/admin/src/ng1/admin/admin.tab.component.js
- web-app/admin/src/ng1/admin/admin.tab.html
- web-app/package-lock.json
- web-app/package.json
This PR fixes an issue where Event managers where able to view the plugins on the admin page.
Admin View:
Event manager view:
> Only Admin users should view plugins

- README.md
- instance/config.js
- instance/package.json
- package-lock.json
- package.json
Updated the `npm` scripts to install, build, and start the server. The current process requires a lot of manual steps
* Added new package.node scripts to simplify the build and launch process
* Updated the README.md build instructions
* Removed the unused `nga-msi` and `random` plugins from the `instance/config.js` to remove errors
git clone git@github.com:ngageoint/mage-server.git
cd mage-server
npm install
npm run build
npm start
npm install # ~53s
npm build # ~38s (without plug-ins)
npm build-all # ~75s (with plug-ins)
> Improve the Mage Build and Run Process

- .vscode/launch.json
Allows the hot reloading of either the Web app or Admin app portions of the app (not the plugins). You can connect to one or Added .vscode/launch.json to share debug configurations the other, and potentially the backend, but I have not successfully tested that workflow.
1. Start the Mage server and web-apps locally (use latest `develop`)
```
cd mage-server
npm install
npm run build
npm start
```
2. Open a new Terminal and Start Admin
```
cd mage-server/web-app
npm run start:app
```
3. In Visual Studio Code, go to the Debug Panel. Choose "Launch WebApp" and hit the "Play" button to open Chrome
Now you should be able to login to the Admin panel of the Mage-Server front end. 
4. Open the Developer tools in Chrome with `Command + Option + I`
5. Navigate to Sources > Page > webpack:// and look …
> Hot Reloading via VS Code

- web-app/admin/src/app/user/user-avatar/user-avatar.component.ts
- web-app/src/app/ingress/ingress.component.ts
- web-app/src/app/user/user-avatar/user-avatar.component.ts
- **Error 1** - When going to the about page, an error is thrown: ERROR TypeError: Cannot read properties of undefined (reading 'nodeVersion'). There are currently versions listed under the 'System section'. Both Node and MongoDB version appear blank.
+ **Solution:** This error seems to have already been fixed, it does not occur.
- **Error 2** - As a user, as I navigate around the mage application if I do not have an avatar picture I see the following error: GET https://abcdemo.mage.geointapps.com/api/users/68127b109cf25890fe279780/avatar 404 (Not Found)
+ **Solution:** Added a more descriptive warning.
- **Error 3** - When logging in, an error shows up: https://abcdemo.mage.geointapps.com/auth/token?createDevice=false 500 internal server error.
+ **Solution:** Replaced the `null` that …
> 1429 - Console Errors

- .github/workflows/aws_dev.deploy.yaml
- .github/workflows/dev.container_build.yaml
- .github/workflows/prod.container_build.yaml
- Dockerfile
- docker-compose.yml
- docker/server/Dockerfile
removes the github action for pushing to the aws dev environment. Now dev and test branches will build dev and test containers that will be added to github packages.
Prod actions created as a first pass. this will not work. Due to how github actions work, I created this as a way to initialize the action for a future card.
> Publish containers as packages
